# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:
  # As a lot of dev dependencies are not supported on ARMv7, we have to test it separately and just test if `npm ci --production` works
  armv7-simple-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ ARMv7 ]
        node: [ 16 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - run: git config --global core.autocrlf false  # Mainly for Windows
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install npm@latest -g
      - run: npm ci --production
